+ integration test for selenium browser commented out for travis since travis does not support Firefox display (for testing just comment in again in your workspace): org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
Error: no display specified